name: CI for Academy Agent

on: 
  push:
    branches:
      [main, dev]
  pull_request:
    branches:
      [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install http server
      run: npm install -g http-server

    - name: Verify sintax
      run: |
        for file in $(find . -name '*.js'); do
          echo "Verificando $file"
          node -c $file
        done

    - name: Set env
      env:
        CI: true
        API_KEY: ${{ secrets.APP_KEY }}
      run: echo "API_KEY é $APP_KEY"

    
